events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location = /ads.txt {
            add_header Content-Type text/plain;
        }

        location /robots.txt {
            add_header Content-Type text/plain;
            return 200 "User-agent: *\nAllow: /\n";
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
