tunnel: 4b1d5bd8-d190-4799-85be-6ab24db0fcc8
credentials-file: /run/tools-secrets/cloudflared/4b1d5bd8-d190-4799-85be-6ab24db0fcc8.json

ingress:
  - hostname: tools.m00h.eu
    service: http://nginx:80
  - hostname: dns.m00h.eu
    service: http://dns-lookup:8080
  - hostname: it.m00h.eu
    service: http://it-tools:80
  - hostname: pdf.m00h.eu
    service: http://stirling:8080
  - hostname: bin.m00h.eu
    service: http://privatebin:8080
  - hostname: go.m00h.eu
    service: http://shlink:8080
  - service: http_status:404
